Repository hh-village/BE, pull requests merged in 2023-04, with the labels that each got.

#22 feat:로그인 기능 구현
  build.gradle
  src/main/java/com/sparta/village/domain/user/controller/UserController.java
  src/main/java/com/sparta/village/domain/user/dto/UserInfoDto.java
  src/main/java/com/sparta/village/domain/user/dto/UserRequestDto.java
  src/main/java/com/sparta/village/domain/user/entity/User.java
  src/main/java/com/sparta/village/domain/user/repository/UserRepository.java
  src/main/java/com/sparta/village/domain/user/service/KakaoUserService.java
  src/main/java/com/sparta/village/domain/user/service/UserService.java
  src/main/java/com/sparta/village/global/jwt/JwtUtil.java
  src/main/resources/application.properties
Labels: enhancement

#23 feat : 제품 등록 기능구현
  src/main/java/com/sparta/village/domain/product/controller/ProductController.java
  src/main/java/com/sparta/village/domain/product/dto/ProductRequestDto.java
  src/main/java/com/sparta/village/domain/product/entity/Product.java
  src/main/java/com/sparta/village/domain/product/repository/ProductRepository.java
  src/main/java/com/sparta/village/domain/product/service/ProductService.java
  src/main/java/com/sparta/village/global/config/WebSecurityConfig.java
Labels: enhancement

#24 feat : 이미지 업로드 기능구현
  build.gradle
  src/main/java/com/sparta/village/domain/image/controller/ImageController.java
  src/main/java/com/sparta/village/domain/image/entity/Image.java
  src/main/java/com/sparta/village/domain/image/repository/ImageRepository.java
  src/main/java/com/sparta/village/domain/image/service/ImageStorageService.java
  src/main/java/com/sparta/village/global/config/S3Config.java
  src/main/java/com/sparta/village/global/config/WebSecurityConfig.java
Labels: enhancement

#25 feat : 위치서비스 기능구현 (지오코드)
  src/main/java/com/sparta/village/domain/naver/controller/MapController.java
  src/main/java/com/sparta/village/domain/naver/service/NaverMapService.java
  src/main/java/com/sparta/village/global/config/WebSecurityConfig.java
Labels: enhancement

#40 fix : Url변수 받아서 파일이름 변환
  src/main/java/com/sparta/village/domain/image/service/ImageStorageService.java
Labels: bug, enhancement

#46 feat : 제품 상세페이지 기능구현 완료
  src/main/java/com/sparta/village/domain/image/repository/ImageRepository.java
  src/main/java/com/sparta/village/domain/image/service/ImageStorageService.java
  src/main/java/com/sparta/village/domain/product/controller/ProductController.java
  src/main/java/com/sparta/village/domain/product/dto/ProductDetailResponseDto.java
  src/main/java/com/sparta/village/domain/product/service/ProductService.java
  src/main/java/com/sparta/village/domain/reservation/service/ReservationService.java
  src/main/java/com/sparta/village/domain/user/service/KakaoUserService.java
Labels: enhancement

#50 docs : 코드 컨벤션, 자잘한 리팩토링
  src/main/java/com/sparta/village/domain/image/controller/ImageController.java
  src/main/java/com/sparta/village/domain/image/service/ImageStorageService.java
  src/main/java/com/sparta/village/domain/naver/controller/MapController.java
  src/main/java/com/sparta/village/domain/naver/service/NaverMapService.java
  src/main/java/com/sparta/village/domain/product/controller/ProductController.java
  src/main/java/com/sparta/village/domain/product/service/ProductService.java
Labels: documentation

#56 feat : 검색기능 구현
  src/main/java/com/sparta/village/domain/product/controller/ProductController.java
  src/main/java/com/sparta/village/domain/product/repository/ProductRepository.java
  src/main/java/com/sparta/village/domain/product/service/ProductService.java
Labels: enhancement

#59 fix : 검색기능 구현 (이미지가 불러와지지 않아 추가 수정)
  src/main/java/com/sparta/village/domain/product/entity/Product.java
  src/main/java/com/sparta/village/domain/product/service/ProductService.java
Labels: bug, enhancement

#61 fix : 거래체결 기능구현 (영미님 코드 따라하기)
  src/main/java/com/sparta/village/domain/product/service/ProductService.java
  src/main/java/com/sparta/village/domain/reservation/controller/ReservationController.java
  src/main/java/com/sparta/village/domain/reservation/dto/AcceptReservationResponseDto.java
  src/main/java/com/sparta/village/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/sparta/village/domain/reservation/service/ReservationService.java
Labels: enhancement

#69 feat: 채팅 기능 1차 구현
  build.gradle
  src/main/java/com/sparta/village/domain/chat/controller/ChatMessageController.java
  src/main/java/com/sparta/village/domain/chat/controller/ChatRoomController.java
  src/main/java/com/sparta/village/domain/chat/dto/ChatMessageDto.java
  src/main/java/com/sparta/village/domain/chat/dto/ChatMessageResponseDto.java
  src/main/java/com/sparta/village/domain/chat/dto/MessageListDto.java
  src/main/java/com/sparta/village/domain/chat/dto/RoomListDto.java
  src/main/java/com/sparta/village/domain/chat/entity/ChatMessage.java
  src/main/java/com/sparta/village/domain/chat/entity/ChatRoom.java
  src/main/java/com/sparta/village/domain/chat/repository/ChatMessageRepository.java
  src/main/java/com/sparta/village/domain/chat/repository/ChatRoomRepository.java
  src/main/java/com/sparta/village/domain/chat/service/ChatRoomService.java
  src/main/java/com/sparta/village/domain/user/service/KakaoUserService.java
  src/main/java/com/sparta/village/global/config/WebSecurityConfig.java
  src/main/java/com/sparta/village/global/config/WebSocketConfig.java
  src/main/java/com/sparta/village/global/exception/ErrorCode.java
  src/test/java/com/sparta/village/reservation/ReservationRepositoryTest.java
  src/test/java/com/sparta/village/reservation/ReservationServiceTest.java
Labels: enhancement

#72 fix : 유저정보 subject값 수정
  src/main/java/com/sparta/village/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/sparta/village/domain/reservation/service/ReservationService.java
  src/main/java/com/sparta/village/domain/user/repository/UserRepository.java
  src/main/java/com/sparta/village/domain/user/service/KakaoUserService.java
  src/main/java/com/sparta/village/global/jwt/JwtUtil.java
  src/main/java/com/sparta/village/global/security/UserDetailsImpl.java
  src/main/java/com/sparta/village/global/security/UserDetailsServiceImpl.java
Labels: bug, enhancement

#78 fix : 전체게시글 목록에 이미지 추가하기
  src/main/java/com/sparta/village/domain/product/dto/ProductResponseDto.java
  src/main/java/com/sparta/village/domain/product/entity/Product.java
  src/main/java/com/sparta/village/domain/product/service/ProductService.java
Labels: bug, enhancement

#79 fix : 상세페이지 응답값 오류사항 수정
  src/main/java/com/sparta/village/domain/product/service/ProductService.java
  src/main/java/com/sparta/village/domain/reservation/dto/ReservationResponseDto.java
  src/main/java/com/sparta/village/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/sparta/village/domain/reservation/service/ReservationService.java
  src/main/resources/application.properties
Labels: bug, enhancement

#81 feat: 유저이름 변경 및 제품등록조회와 대여조회
  build.gradle
  src/main/java/com/sparta/village/domain/chat/controller/ChatMessageController.java
  src/main/java/com/sparta/village/domain/image/entity/Image.java
  src/main/java/com/sparta/village/domain/image/repository/ImageRepository.java
  src/main/java/com/sparta/village/domain/product/controller/ProductController.java
  src/main/java/com/sparta/village/domain/product/dto/MyProductResponseDto.java
  src/main/java/com/sparta/village/domain/product/dto/ProductDetailResponseDto.java
  src/main/java/com/sparta/village/domain/product/dto/ProductRequestDto.java
  src/main/java/com/sparta/village/domain/product/dto/ProductResponseDto.java
  src/main/java/com/sparta/village/domain/product/entity/Product.java
  src/main/java/com/sparta/village/domain/product/repository/ProductRepository.java
  src/main/java/com/sparta/village/domain/product/service/ProductService.java
  src/main/java/com/sparta/village/domain/reservation/controller/ReservationController.java
  src/main/java/com/sparta/village/domain/reservation/dto/RentResponseDto.java
  src/main/java/com/sparta/village/domain/reservation/dto/ReservationResponseDto.java
  src/main/java/com/sparta/village/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/sparta/village/domain/reservation/service/ReservationService.java
  src/main/java/com/sparta/village/domain/user/controller/UserController.java
  src/main/java/com/sparta/village/domain/user/dto/NicknameRequestDto.java
  src/main/java/com/sparta/village/domain/user/entity/User.java
  src/main/java/com/sparta/village/domain/user/repository/UserRepository.java
  src/main/java/com/sparta/village/domain/user/service/KakaoUserService.java
  src/main/java/com/sparta/village/domain/user/service/UserService.java
  src/main/java/com/sparta/village/global/exception/CustomExceptionHandler.java
  src/main/java/com/sparta/village/global/exception/ErrorCode.java
  src/main/java/com/sparta/village/global/security/UserDetailsImpl.java
Labels: enhancement

#85 feat : 찜 기능구현
  src/main/java/com/sparta/village/domain/product/controller/ProductController.java
  src/main/java/com/sparta/village/domain/product/dto/ProductDetailResponseDto.java
  src/main/java/com/sparta/village/domain/product/service/ProductService.java
  src/main/java/com/sparta/village/domain/zzim/controller/ZzimController.java
  src/main/java/com/sparta/village/domain/zzim/entity/Zzim.java
  src/main/java/com/sparta/village/domain/zzim/repository/ZzimRepository.java
  src/main/java/com/sparta/village/domain/zzim/service/ZzimService.java
Labels: enhancement

#88 feat : 마이페이지 기능 통합하여 구현
  src/main/java/com/sparta/village/domain/image/repository/ImageRepository.java
  src/main/java/com/sparta/village/domain/product/controller/ProductController.java
  src/main/java/com/sparta/village/domain/product/dto/ProductDetailResponseDto.java
  src/main/java/com/sparta/village/domain/product/dto/ProductResponseDto.java
  src/main/java/com/sparta/village/domain/product/entity/Product.java
  src/main/java/com/sparta/village/domain/product/repository/ProductRepository.java
  src/main/java/com/sparta/village/domain/product/service/ProductService.java
  src/main/java/com/sparta/village/domain/reservation/controller/ReservationController.java
  src/main/java/com/sparta/village/domain/reservation/entity/Reservation.java
  src/main/java/com/sparta/village/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/sparta/village/domain/reservation/service/ReservationService.java
  src/main/java/com/sparta/village/domain/user/controller/UserController.java
  src/main/java/com/sparta/village/domain/user/dto/MyPageResponseDto.java
  src/main/java/com/sparta/village/domain/user/dto/MyProductsResponseDto.java
  src/main/java/com/sparta/village/domain/user/dto/MyReservationsResponseDto.java
  src/main/java/com/sparta/village/domain/user/dto/ZzimsResponseDto.java
  src/main/java/com/sparta/village/domain/user/service/UserService.java
  src/main/java/com/sparta/village/domain/zzim/entity/Zzim.java
  src/main/java/com/sparta/village/domain/zzim/repository/ZzimRepository.java
  src/main/java/com/sparta/village/global/exception/ErrorCode.java
Labels: bug, enhancement

#92 feat : 인기품목 표시 기능구현
  src/main/java/com/sparta/village/domain/product/controller/ProductController.java
  src/main/java/com/sparta/village/domain/product/dto/MainResponseDto.java
  src/main/java/com/sparta/village/domain/product/dto/ProductResponseDto.java
  src/main/java/com/sparta/village/domain/product/entity/Product.java
  src/main/java/com/sparta/village/domain/product/repository/ProductRepository.java
  src/main/java/com/sparta/village/domain/product/service/ProductService.java
  src/main/java/com/sparta/village/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/sparta/village/domain/user/controller/UserController.java
  src/main/java/com/sparta/village/domain/user/service/UserService.java
  src/main/java/com/sparta/village/domain/zzim/entity/Zzim.java
  src/main/java/com/sparta/village/domain/zzim/repository/ZzimRepository.java
  src/main/java/com/sparta/village/domain/zzim/service/ZzimService.java
Labels: bug, documentation, enhancement

#95 feat: 제품 수정 기능 구현
  src/main/java/com/sparta/village/domain/image/service/ImageStorageService.java
  src/main/java/com/sparta/village/domain/product/controller/ProductController.java
  src/main/java/com/sparta/village/domain/product/entity/Product.java
  src/main/java/com/sparta/village/domain/product/service/ProductService.java
Labels: bug, enhancement

#97 fix : 제품 삭제시 채팅 메세지, 채팅룸, 예약, 찜, 이미지 삭제 될수 있게 기능수정
  src/main/java/com/sparta/village/domain/chat/repository/ChatMessageRepository.java
  src/main/java/com/sparta/village/domain/chat/repository/ChatRoomRepository.java
  src/main/java/com/sparta/village/domain/chat/service/ChatRoomService.java
  src/main/java/com/sparta/village/domain/product/service/ProductService.java
  src/main/java/com/sparta/village/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/sparta/village/domain/zzim/entity/Zzim.java
  src/main/java/com/sparta/village/domain/zzim/repository/ZzimRepository.java
Labels: bug, enhancement

#99 fix : 업데이트 로직 생성
  src/main/java/com/sparta/village/domain/product/service/ProductService.java
Labels: bug, enhancement

#102 docs : 리팩토링
  src/main/java/com/sparta/village/domain/chat/service/ChatRoomService.java
  src/main/java/com/sparta/village/domain/image/repository/ImageRepository.java
  src/main/java/com/sparta/village/domain/image/service/ImageStorageService.java
  src/main/java/com/sparta/village/domain/product/service/ProductService.java
  src/main/java/com/sparta/village/domain/reservation/dto/ReservationCountResponseDto.java
  src/main/java/com/sparta/village/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/sparta/village/domain/reservation/service/ReservationService.java
  src/main/java/com/sparta/village/domain/user/dto/MyProductsResponseDto.java
  src/main/java/com/sparta/village/domain/user/dto/MyReservationsResponseDto.java
  src/main/java/com/sparta/village/domain/user/dto/ZzimsResponseDto.java
  src/main/java/com/sparta/village/domain/user/service/UserService.java
  src/main/java/com/sparta/village/domain/zzim/repository/ZzimRepository.java
  src/main/java/com/sparta/village/domain/zzim/service/ZzimService.java
Labels: bug, enhancement

#107 fix : 찜서비스 삭제 오류 수정
  src/main/java/com/sparta/village/domain/zzim/repository/ZzimRepository.java
  src/main/java/com/sparta/village/domain/zzim/service/ZzimService.java
Labels: bug

#108 fix : 찜 기능 오류수정
  src/main/java/com/sparta/village/domain/zzim/repository/ZzimRepository.java
  src/main/java/com/sparta/village/domain/zzim/service/ZzimService.java
Labels: bug

#113 fix : 프로필 url경로 추가
  src/main/java/com/sparta/village/domain/reservation/dto/ReservationResponseDto.java
  src/main/java/com/sparta/village/domain/reservation/service/ReservationService.java
  src/main/java/com/sparta/village/domain/user/service/UserService.java
Labels: bug, documentation

#121 fix : put매핑 patch로 변경
  src/main/java/com/sparta/village/domain/product/controller/ProductController.java
Labels: bug, documentation

#122 fix : put매핑 patch로 변경
  src/main/java/com/sparta/village/domain/product/controller/ProductController.java
Labels: documentation

#123 fix : 이미지 있을때만 삭제 및 업로드 할수 있게 코드 추가
  src/main/java/com/sparta/village/domain/product/service/ProductService.java
Labels: bug, enhancement

#127 docs : cors config에 프론트 배포 url추가
  src/main/java/com/sparta/village/global/config/CorsConfig.java
Labels: documentation

#128 docs : corsconfig, 프로퍼티 리다이렉트 url 수정
  src/main/java/com/sparta/village/global/config/CorsConfig.java
Labels: documentation

#137 docs : testCode 기능구현
  src/main/java/com/sparta/village/domain/image/entity/Image.java
  src/main/java/com/sparta/village/domain/naver/service/NaverMapService.java
  src/main/java/com/sparta/village/domain/product/dto/ProductRequestDto.java
  src/main/java/com/sparta/village/domain/product/entity/Product.java
  src/main/java/com/sparta/village/domain/product/repository/ProductRepository.java
  src/main/java/com/sparta/village/domain/product/service/ProductService.java
  src/main/java/com/sparta/village/domain/reservation/dto/ReservationCountResponseDto.java
  src/main/java/com/sparta/village/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/sparta/village/domain/user/entity/User.java
  src/test/java/com/sparta/village/domain/image/service/ImageStorageServiceTest.java
  src/test/java/com/sparta/village/domain/naver/service/NaverMapServiceTest.java
  src/test/java/com/sparta/village/domain/product/service/ProductServiceTest.java
  src/test/java/com/sparta/village/domain/zzim/service/ZzimServiceTest.java
Labels: documentation

#138 test : update 테스트 코드 수정
  src/test/java/com/sparta/village/domain/product/service/ProductServiceTest.java
Labels: documentation

#142 test : 어노테이션 extendWith로 전체 수정 및 테스트 확인(코드 하나 하나당 빠진 테스트 다시 체크)
  src/test/java/com/sparta/village/domain/image/service/ImageStorageServiceTest.java
  src/test/java/com/sparta/village/domain/naver/service/NaverMapServiceTest.java
  src/test/java/com/sparta/village/domain/product/service/ProductServiceTest.java
  src/test/java/com/sparta/village/domain/zzim/service/ZzimServiceTest.java
Labels: bug, documentation

#145 test : productService 검색 테스트 수정
  src/main/java/com/sparta/village/domain/product/service/ProductService.java
  src/test/java/com/sparta/village/domain/product/service/ProductServiceTest.java
Labels: documentation

#146 test : userService 테스트코드 기능구현
  src/main/java/com/sparta/village/domain/reservation/entity/Reservation.java
  src/main/java/com/sparta/village/domain/zzim/entity/Zzim.java
  src/test/java/com/sparta/village/domain/product/service/ProductServiceTest.java
  src/test/java/com/sparta/village/domain/user/service/UserServiceTest.java
Labels: documentation

#147 docs : 제품등록시 공백 예외처리 추가
  src/main/java/com/sparta/village/domain/product/dto/ProductRequestDto.java
Labels: documentation

#148 docs : 제품등록시 공백 예외처리 추가
  build.gradle
  src/main/generated/com/sparta/village/domain/chat/entity/QChatMessage.java
  src/main/generated/com/sparta/village/domain/chat/entity/QChatRoom.java
  src/main/generated/com/sparta/village/domain/image/entity/QImage.java
  src/main/generated/com/sparta/village/domain/product/entity/QProduct.java
  src/main/generated/com/sparta/village/domain/reservation/entity/QReservation.java
  src/main/generated/com/sparta/village/domain/reservation/entity/QTimestamped.java
  src/main/generated/com/sparta/village/domain/user/entity/QUser.java
  src/main/generated/com/sparta/village/domain/zzim/entity/QZzim.java
  src/main/java/com/sparta/village/domain/chat/controller/ChatController.java
  src/main/java/com/sparta/village/domain/chat/dto/ChatMessageResponseDto.java
  src/main/java/com/sparta/village/domain/chat/dto/MessageListDto.java
  src/main/java/com/sparta/village/domain/chat/dto/MyChatRoomResponseDto.java
  src/main/java/com/sparta/village/domain/chat/entity/ChatMessage.java
  src/main/java/com/sparta/village/domain/chat/repository/ChatMessageRepository.java
  src/main/java/com/sparta/village/domain/chat/service/ChatService.java
  src/main/java/com/sparta/village/domain/product/controller/ProductController.java
  src/main/java/com/sparta/village/domain/product/dto/ProductDetailResponseDto.java
  src/main/java/com/sparta/village/domain/product/dto/ProductRequestDto.java
  src/main/java/com/sparta/village/domain/product/dto/SearchResponseDto.java
  src/main/java/com/sparta/village/domain/product/repository/ProductRepository.java
  src/main/java/com/sparta/village/domain/product/repository/SearchQueryRepository.java
  src/main/java/com/sparta/village/domain/product/service/ProductService.java
  src/main/java/com/sparta/village/domain/reservation/entity/Reservation.java
  src/main/java/com/sparta/village/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/sparta/village/domain/reservation/service/ReservationService.java
  src/main/java/com/sparta/village/domain/user/controller/UserController.java
  src/main/java/com/sparta/village/domain/user/service/UserService.java
  src/main/java/com/sparta/village/domain/zzim/entity/Zzim.java
  src/main/java/com/sparta/village/global/config/WebSecurityConfig.java
  src/main/java/com/sparta/village/global/exception/ErrorCode.java
  src/test/java/com/sparta/village/chat/ChatServiceTest.java
  src/test/java/com/sparta/village/domain/image/service/ImageStorageServiceTest.java
  src/test/java/com/sparta/village/domain/naver/service/NaverMapServiceTest.java
  src/test/java/com/sparta/village/domain/product/service/ProductServiceTest.java
  src/test/java/com/sparta/village/domain/user/service/UserServiceTest.java
  src/test/java/com/sparta/village/domain/zzim/service/ZzimServiceTest.java
Labels: documentation

#150 test : ProductController 테스트 코드
  src/test/java/com/sparta/village/domain/product/controller/ProductControllerTest.java
Labels: documentation

#152 test : MapController 테스트 코드
  src/test/java/com/sparta/village/domain/naver/controller/MapControllerTest.java
Labels: documentation

#154 test : ZzimController 테스트 코드
  src/test/java/com/sparta/village/domain/zzim/controller/ZzimControllerTest.java
Labels: documentation

#158 feat : 누적방문자수 기능구현 (redis, scheduler)
  build.gradle
  src/main/java/com/sparta/village/VillageApplication.java
  src/main/java/com/sparta/village/domain/product/dto/MainResponseDto.java
  src/main/java/com/sparta/village/domain/product/service/ProductService.java
  src/main/java/com/sparta/village/domain/visitor/entity/Visitor.java
  src/main/java/com/sparta/village/domain/visitor/repository/VisitorCountRepository.java
  src/main/java/com/sparta/village/domain/visitor/scheduler/VisitorCountScheduler.java
  src/main/java/com/sparta/village/global/config/RedisConfig.java
  src/main/java/com/sparta/village/global/config/WebMvcConfig.java
  src/main/java/com/sparta/village/global/interceptor/VisitInterceptor.java
Labels: enhancement

#159 feat : 누적 방문자수 기능구현 (메인페이지)
  build.gradle
  src/main/java/com/sparta/village/VillageApplication.java
  src/main/java/com/sparta/village/domain/image/service/ImageStorageService.java
  src/main/java/com/sparta/village/domain/product/dto/MainResponseDto.java
  src/main/java/com/sparta/village/domain/product/service/ProductService.java
  src/main/java/com/sparta/village/domain/visitor/entity/Visitor.java
  src/main/java/com/sparta/village/domain/visitor/repository/VisitorCountRepository.java
  src/main/java/com/sparta/village/domain/visitor/scheduler/VisitorCountScheduler.java
  src/main/java/com/sparta/village/global/config/RedisConfig.java
  src/main/java/com/sparta/village/global/config/WebMvcConfig.java
  src/main/java/com/sparta/village/global/config/WebSecurityConfig.java
  src/main/java/com/sparta/village/global/interceptor/VisitInterceptor.java
  src/test/java/com/sparta/village/domain/naver/controller/MapControllerTest.java
  src/test/java/com/sparta/village/domain/product/controller/ProductControllerTest.java
  src/test/java/com/sparta/village/domain/zzim/controller/ZzimControllerTest.java
Labels: documentation, enhancement
